all: functions.o log.class.o request.class.o config.class.o

functions.o: functions.cpp
	g++ -c functions.cpp
log.class.o: log.class.cpp
	g++ -c log.class.cpp
request.class.o: request.class.cpp
	g++ -c request.class.cpp
config.class.o: config.class.cpp
	g++ -c config.class.cpp